#!/usr/bin/env bash

cat << EOF | sudo tee /lib/systemd/system/ttyS0.service
[Unit]
Description=Serial Console Service

[Service]
ExecStart=/sbin/getty -L 115200 ttyS0 vt102
Restart=always

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable ttyS0
sudo systemctl start ttyS0

echo "root:gprm8350" | sudo chpasswd

sudo apt update -y && sudo apt-get install -y git vim net-tools wget curl bash-completion apt-utils tcpdump gnupg2

sudo chmod -x /etc/update-motd.d/*

cat << EOF | sudo tee /etc/update-motd.d/01-custom
#!/bin/sh
echo "****************************WARNING****************************************
UNAUTHORISED ACCESS IS PROHIBITED. VIOLATORS WILL BE PROSECUTED.
*********************************************************************************"
EOF

sudo chmod +x /etc/update-motd.d/01-custom

cat << EOF | sudo tee /etc/modprobe.d/qemu-system-x86.conf
options kvm_intel nested=1
EOF

cat << EOF | sudo tee /etc/modules-load.d/modules.conf
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with # are ignored.
mpls_router
mpls_iptunnel
EOF

sudo mkdir -p /etc/systemd/system/networking.service.d

cat << EOF | sudo tee /etc/systemd/system/networking.service.d/reduce-timeout.conf
[Service]
TimeoutStartSec=15
EOF

sudo apt update -y && sudo apt install ifupdown2 iproute2 bridge-utils vlan -y
sudo apt-get remove --purge resolvconf -y
