#!/usr/bin/env bash

cat << EOF | sudo tee /lib/systemd/system/ttyS0.service
[Unit]
Description=Serial Console Service
[Service]
ExecStart=/sbin/getty -L 115200 ttyS0 vt102
Restart=always
[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable ttyS0
sudo systemctl start ttyS0

echo "root:gprm8350" | sudo chpasswd

sudo apt update -y && sudo apt-get install -y git vim net-tools wget curl bash-completion apt-utils base-files ifupdown rsyslog tcpdump gnupg2 iproute2 socat telnet libc-ares2 libjson-c3 python-ipaddr python3-jinja2 lsb-release

cat << EOF | sudo tee /etc/modprobe.d/qemu-system-x86.conf
options kvm_intel nested=1
EOF

cat << EOF | sudo tee /etc/modules-load.d/modules.conf
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with # are ignored.
mpls_router
mpls_gso
mpls_iptunnel
EOF

sudo mkdir -p /etc/systemd/system/networking.service.d

cat << EOF | sudo tee /etc/systemd/system/networking.service.d/reduce-timeout.conf
[Service]
TimeoutStartSec=15
EOF

sudo DEBIAN_FRONTEND=noninteractive apt-get update --no-install-recommends --fix-missing -y
sudo DEBIAN_FRONTEND=noninteractive apt full-upgrade --no-install-recommends -y && sudo DEBIAN_FRONTEND=noninteractive apt dist-upgrade -y

# Install flexiWAN
curl -sL https://deb.flexiwan.com/setup | sudo -E bash -
sudo apt update -y && sudo apt-get install -y flexiwan-router

cat << EOF | sudo tee /lib/systemd/system/intconf.service
[Unit]
Description=Interface Configuration Service

[Service]
ExecStart=/root/intconf.sh

[Install]
WantedBy=multi-user.target
EOF

cat << EOF | sudo tee /root/intconf.sh
#!/bin/bash
#

service vpp start
sleep 10
vppctl enable tap-inject

EOF

sudo chmod +x /root/intconf.sh
sudo systemctl daemon-reload
sudo systemctl enable intconf
sudo systemctl start intconf

sudo apt update -y
sudo DEBIAN_FRONTEND=noninteractive apt-get install linux-generic-hwe-18.04 --install-recommends -y
sudo apt autoremove -y && sudo apt --fix-broken install -y

sudo chmod -x /etc/update-motd.d/*

cat << EOF | sudo tee /etc/update-motd.d/01-custom
#!/bin/sh
echo "****************************WARNING****************************************
UNAUTHORISED ACCESS IS PROHIBITED. VIOLATORS WILL BE PROSECUTED.
*********************************************************************************"
EOF

sudo chmod +x /etc/update-motd.d/01-custom
