Vagrant.configure("2") do |config|
  config.vm.define "unf" do |unf|
      unf.vm.box = "generic/ubuntu1804"
      unf.vm.hostname = "unf"
      unf.vm.provision "shell", path: "gen_provisioning-unf"
      unf.vm.provision :reload
      unf.vm.provision "shell", path: "vpp_install"
      unf.vm.provision :reload
      unf.vm.provider "virtualbox" do |vbox|
            vbox.name = "unf"
            vbox.memory = 16384
            vbox.cpus = 4
            vbox.customize ["modifyvm", :id, "--chipset", "ich9"]
            vbox.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
      end
  end
end
