#!/usr/bin/env bash

# Modify interface management

sudo mkdir -p /etc/network/interfaces.d

cat << EOF | sudo tee /etc/network/interfaces
auto lo
iface lo inet loopback
    address 127.0.0.2/32
    
auto eth0
allow-hotplug eth0
iface eth0 inet dhcp
    mtu 9000
    
source /etc/network/interfaces.d/*.cfg
EOF

sudo apt install ifupdown2 -y && sudo apt remove netplan.io libnetplan0 -y && sudo rm -rf /etc/netplan/*.yml
