#!/usr/bin/env bash

# Install VPP

git clone https://gitlab.com/flexiwangroup/flexirouter.git && cd /home/vagrant/flexirouter && git checkout ad7e8c26a1d7d08e1d3eda40784d1c7d418565e6 && \
git clone https://gitlab.com/flexiwangroup/flexiroutervpp.git vpp && cd vpp && git checkout 711f6d63f073f2285e4bae4cab09feaca23438c2 && \
cd /home/vagrant/flexirouter && git clone https://gitlab.com/flexiwangroup/flexiroutersb.git vppsb && cd vppsb && \
git checkout cf96cfe4d5e335600aedc19ce16b099f86fc7e0a && cd /home/vagrant/flexirouter && \
cp /home/vagrant/flexirouter/scripts/prepare.sh /home/vagrant/flexirouter && cp /home/vagrant/flexirouter/scripts/vpp_build.sh /home/vagrant/flexirouter && \
cp /home/vagrant/flexirouter/scripts/vpp_install.sh /home/vagrant/flexirouter && \
cp /home/vagrant/flexirouter/scripts/vpp_build_and_install.sh /home/vagrant/flexirouter && \
sed -i 's/install-ext-deps/UNATTENDED=yes install-ext-deps/' prepare.sh && sed -i 's/install-dep/UNATTENDED=yes install-dep/' prepare.sh && \
sudo -H ./prepare.sh && sudo -H ./vpp_build_and_install.sh && cd /home/vagrant/flexirouter/vpp && \
sudo make pkg-deb && sudo dpkg -i /home/vagrant/flexirouter/vpp/build-root/*.deb

cat << EOF | sudo tee /lib/systemd/system/intconf.service
[Unit]
Description=Interface Configuration Service
[Service]
ExecStart=/root/intconf.sh
[Install]
WantedBy=multi-user.target
EOF

cat << EOF | sudo tee /root/intconf.sh
#!/bin/bash
#
service vpp start
sleep 10
vppctl enable tap-inject
EOF

sudo chmod +x /root/intconf.sh
sudo systemctl daemon-reload
sudo systemctl enable intconf

#sudo vppctl show ver && sudo service vpp status && sudo vppctl show interface
#sudo vppctl show memory verbose main-heap
#sudo vppctl show run
