#!/bin/bash

/sbin/modprobe uio_pci_generic

ip link set dev eth1 down
ip link set dev eth2 down

cd vpp

gdb --args ./home/vagrant/flexirouter/vpp/build-root/build-vpp_debug-native/vpp/bin/vpp -c ../scripts/startup.conf

cd -

python /home/vagrant/flexirouter/vpp/extras/vpp_config/scripts/dpdk-devbind.py -b e1000 00:03.0 00:08.0

ip link set dev eth1 up
ip link set dev eth2 up
